config/routes.rb
Rails.application.routes.draw do
	scope "(:locale)", locale: /#{I18n.available_locales.map(&:to_s).join("|")}/ do
		root 'records#new'
		get '/records', to: 'records#new'
		get 'terms', to: 'records#terms'
	  get 'privacy_policy', to: 'records#privacy_policy'
		resources :records, only: %i[create]
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  def set_locale
    I18n.locale = locale
  end

  def locale
    @locale ||= params[:locale] ||= I18n.default_locale
  end

  def default_url_options(options = {})
    options.merge(locale: locale)
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  def new
    @record = RecordsForm.new
  end

  def create
    @record = RecordsForm.new(record_params)
    if @record.valid?
    post_pdf = NotificationPdf::PostPdf.new(@record).render
      send_data post_pdf,
        filename: 'post_pdf.pdf',
        type: 'application/pdf',
        disposition: 'inline' #PDFをブラウザ上に出力　外すとダウンロード
    else
      render :new
    end
  end

  def terms; end

  def privacy_policy; end

  private

  def record_params
    params.require(:records_form).permit(:myname, :stamp, :old, :fromdate, :todate, :yourname, :getup, :cleanup, :remark)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = I18n.t('defaults.title')

    page_title.empty? ? base_title : page_title + " | " + base_title
  end

  def default_meta_tags
    {
      site: I18n.t('defaults.site'),
      title: I18n.t('defaults.title'),
      description: I18n.t('defaults.description'),
      keywords: '反抗期 PDF, 反抗期 反抗期届, 反抗期 ソフト, 反抗期 届け、反抗期, REBELLION NOTICE, LITTLE REBELLION, notification, a rebellion period, 叛乱通知',
      charset: 'UTF-8',
      icon: [
        { href: image_url('children_crossing.png') },
        { href: image_url('children_crossing.png'), rel: 'apple-touch-icon', sizes: '180x180', type: 'img/png' },
      ],
      og: {
        site_name: I18n.t('defaults.site'),
        title: I18n.t('defaults.title'),
        description: I18n.t('defaults.description'), 
        type: 'website',
        url: request.original_url,
        image: image_url('ogp.png'),
        locale: 'ja_JP',
      },
      twitter: {
        card: 'summary_large_image',
        site: '@eityamo',
      }
    }
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- ogp -->
    <%= display_meta_tags(default_meta_tags) %>

    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-GRVBKEM4C8"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
    
      gtag('config', 'G-GRVBKEM4C8');
    </script>
  </head>

  <body>
  <div class="bg-white pb-6 sm:pb-8 lg:pb-12">
    <div class="max-w-screen-2xl px-4 md:px-8 mx-auto">
      <%= render 'shared/header' %>
      <%= yield %>
    </div>
  </div>
  <%= render 'shared/footer' %>
  </body>
</html>

<%#
<script>
const moons = ['🌑', '🌒', '🌓', '🌔', '🌕', '🌖', '🌗', '🌘', '🌑', '🌘', '🌗', '🌖', '🌖', '🌕', '🌔', '🌓', '🌒'];
let count = 0;
setInterval(()=> {
    location.hash = moons[count % moons.length];
    count++;
}, 200);
</script>
%>
<script>
document.getElementById('scroll-down').addEventListener('click', () => {
// formの表示位置を取得
  var form = document.getElementById('form');
// formまでスクロール
    form.scrollIntoView({
        behavior: "smooth",
        block: "start",
        inline: "start"
    });
});
</script>

app/views/records/new.html.erb
<% set_meta_tags title: '反抗期届', description: 'ディスクリプション' %>

<section class="flex justify-center items-center flex-1 shrink-0 bg-gray-100 overflow-hidden shadow-lg rounded-lg relative py-12 md:py-12 xl:py-24">
  <!-- image - start -->
  <%= image_tag 'top4.png', class: "w-full h-full object-cover object-center absolute inset-0" %>
  <!-- img src="https://images.unsplash.com/photo-1618004652321-13a63e576b80?auto=format&q=75&fit=crop&w=1500" loading="lazy" alt="Photo by Fakurian Design" class="w-full h-full object-cover object-center absolute inset-0" /-->
  <!-- image - end -->

  <!-- overlay - start -->
  <div class="bg-indigo-500 mix-blend-multiply absolute inset-0"></div>
  <!-- overlay - end -->

  <!-- text start -->
  <div class="sm:max-w-xl flex flex-col items-center relative p-4">
    <h1 class="titile text-white text-5xl sm:text-5xl md:text-7xl font-bold text-center mt-8 md:mt-20 mb-8 md:mb-8"><%= t '.title' %></h1>
    <p class="text-white text-2xl md:text-4xl sm:text-2xl text-center mb-4 md:mb-16 mt-8 md:mt-20"><%= t '.subtitle' %></p>
    <p class="text-white text-lg md:text-xl sm:text-xl text-center mb-2 md:mb-8 mt-8 md:mt-12 opacity-75"><%= t '.arrow_down' %></p>
    <button class="scroll-down-dude text-center" id="scroll-down"></button>
  </div>
  <!-- text end -->
</section>

<div class="bg-white py-6 sm:py-8 lg:py-12" id="form">
  <div class="max-w-screen-2xl px-4 md:px-8 mx-auto">
      <%#= image_tag 'clipboard_brown1.png', class:"w-full h-full object-contain object-center absolute inset-0" %>
    <!-- text - start -->
    <div class="mb-10 md:mb-8">
      <h2 class="text-gray-800 text-2xl lg:text-5xl font-bold text-center mb-4 md:mb-10"><%= t '.form_title' %></h2>

      <p class="max-w-screen-md text-gray-500 md:text-lg mx-auto"><%= t '.form_header1' %><br><%= t '.form_header2' %><br><%= t '.form_header3' %></p>
    </div>
    <!-- text - end -->

    <!-- form - start -->
    <%= form_with  model: @record, url: records_path, local: true, class: "max-w-screen-md grid sm:grid-cols-2 gap-4 mx-auto" do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="sm:col-span-2">
        <%= f.label :myname %>
        <%= f.text_field :myname, placeholder: t('.name_placeholder'), maxlength: "10", class: "bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full px-3 py-2 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"  %>
      </div>

      <div class="inline-block relative w-48">
        <%= f.label :stamp %>
        <%= f.text_field :stamp, placeholder: t('.stamp_placeholder'), maxlength: "4", class: "bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full px-3 py-2 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"  %>
      </div>

      <div class="inline-block relative w-48">
        <%= f.label :old %>
        <%= f.number_field :old, in: 1..99, class: "bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full px-3 py-2 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
      </div>

      <div date-rangepicker, class="sm:col-span-2 flex flex-col">
        <%= f.label :fromdate %>
        <div class="flex">
          <%= f.date_field :fromdate, class:"text-center bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full md:w-auto px-3 py-2 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
        <span class="mx-4 text-gray-500 my-auto">〜</span>
          <%= f.date_field :todate, class:"text-center bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full md:w-auto px-3 py-2 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
        </div>
      </div>
      
      <div class="sm:col-span-2">
        <%= f.label :yourname%>
        <%= f.text_field :yourname, placeholder: t('.name_placeholder'), maxlength: "10", class: "bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full px-3 py-2 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"  %>
      </div>

      <div class="inline-block relative w-48">
        <%= f.label :getup %>
        <%= f.select :getup, [t('.necessary'), t('.unnecessary'), t('.consultation')],  { include_blank: true }, class:"text-center bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full px-3 py-2 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
      </div>

      <div class="inline-block relative w-48">
        <%= f.label :cleanup %>
        <%= f.select :cleanup, [t('.necessary'), t('.unnecessary'), t('.consultation')],  { include_blank: true }, class:"text-center bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full px-3 py-2 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
      </div>

      <div class="sm:col-span-2">
        <%= f.label :remark %>
        <%= f.text_area :remark, placeholder: t('.remarks_placeholder'), maxlength: "130", class: "bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full duration-100 px-3 py-2 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"  %>
      </div>

      <div class="sm:col-span-2 flex justify-between items-center">
        <%= f.submit t('.pdf'), class: "inline-block bg-indigo-500 hover:bg-indigo-600 active:bg-indigo-700 focus-visible:ring ring-indigo-300 text-white text-sm md:text-base font-semibold text-center rounded-lg outline-none transition duration-100 px-8 py-3" %>
      </div>
    <% end %>
    <!-- form - end -->
  </div>
</div>

app/views/records/privacy_policy.html.erb
<% set_meta_tags title: 'プライバシーポリシー', noindex: true
 %>
<div class="container mx-auto mt-24">
  <section class="bg-white m-10 p-10 rounded-lg">
    <div class="h3 text-center mb-5">プライバシーポリシー</div>
    届け、反抗期（以下，「当方」といいます。）は，本ウェブサイト上で提供するサービス（以下,「本サービス」といいます。）における，ユーザーの個人情報の取扱いについて，以下のとおりプライバシーポリシー（以下，「本ポリシー」といいます。）を定めます。
    <div class="mb-4">
      <div class="h5">第1条（個人情報）</div>
      「個人情報」とは，個人情報保護法にいう「個人情報」を指すものとし，生存する個人に関する情報であって，当該情報に含まれる氏名，生年月日，住所，電話番号，連絡先その他の記述等により特定の個人を識別できる情報及び容貌，指紋，声紋にかかるデータ，及び健康保険証の保険者番号などの当該情報単体から特定の個人を識別できる情報（個人識別情報）を指します。
    </div>
    <div class="mb-4">
      <div class="h5">第2条（取得する情報）</div>
      当方は、お客様から以下の情報を取得します。
      <div class="list-decimal mt-2">
        <li>氏名(ニックネームやペンネームも含む)</li>
        <li>年齢または生年月日</li>
        <li>OSが生成するID、端末の種類、端末識別子等のお客様が利用するOSや端末に関する情報</li>
        <li>当方ウェブサイトの滞在時間、入力履歴等の当方ウェブサイトにおけるお客様の行動履歴</li>
        <li>当方アプリの起動時間、入力履歴等の当方アプリの利用履歴</li>
      </div>
    </div>
    <div class="mb-4">
      <div class="h5">第3条（個人情報を収集・利用する目的）</div>
      当方は、お客様から取得した情報を、以下の目的のために利用します。
      <div class="list-decimal mt-2">
        <li>当方サービスに関する登録の受付、お客様の本人確認、認証のため</li>
        <li>お客様の当方サービスの利用履歴を管理するため</li>
        <li>当方サービスにおけるお客様の行動履歴を分析し、当方サービスの維持改善に役立てるため</li>
        <li>市場分析、マーケティングのため</li>
        <li>広告の配信、表示及び効果測定のため</li>
        <li>当方のサービスに関するご案内をするため</li>
        <li>当方の規約や法令に違反する行為に対応するため</li>
        <li>以上の他、当方サービスの提供、維持、保護及び改善のため</li>
      </div>
    </div>
    <div class="mb-4">
      <div class="h5">第4条（利用目的の変更）</div>
      当方は，利用目的が変更前と関連性を有すると合理的に認められる場合に限り，個人情報の利用目的を変更するものとします。<br>
      利用目的の変更を行った場合には，変更後の目的について，当方所定の方法により，ユーザーに通知し，または本ウェブサイト上に公表するものとします。
    </div>
    <div class="mb-4">
      <div class="h5">第5条（個人情報の第三者提供）</div>
      当方は、お客様から取得する情報のうち、個人データ（個人情報保護法第２条第６項）に該当するものついては、あらかじめお客様の同意を得ずに、第三者（日本国外にある者を含みます。）に提供しません。<br>
      但し、次の場合は除きます。
      <div class="list-decimal mt-2">
        <li>当方や当方サービスが買収された場合</li>
        <li>事業パートナーと共同利用する場合（具体的な共同利用がある場合は、その内容を別途公表します。）</li>
        <li>その他、法律によって合法的に第三者提供が許されている場合</li>
        <li>当方が利用目的の達成に必要な範囲内において個人情報の取扱いの全部または一部を委託する場合</li>
        <li>合併その他の事由による事業の承継に伴って個人情報が提供される場合</li>
      </div>
    </div>
    <div class="mb-4">
      <div class="h5">第6条（個人情報の利用停止等）</div>
      当方は，本人から，個人情報が，利用目的の範囲を超えて取り扱われているという理由，または不正の手段により取得されたものであるという理由により，その利用の停止または消去（以下，「利用停止等」といいます。）を求められた場合には，遅滞なく必要な調査を行います。<br>
      前項の調査結果に基づき，その請求に応じる必要があると判断した場合には，遅滞なく，当該個人情報の利用停止等を行います。<br>
      当方は，前項の規定に基づき利用停止等を行った場合，または利用停止等を行わない旨の決定をしたときは，遅滞なく，これをユーザーに通知します。<br>
      前2項にかかわらず，利用停止等に多額の費用を有する場合その他利用停止等を行うことが困難な場合であって，ユーザーの権利利益を保護するために必要なこれに代わるべき措置をとれる場合は，この代替策を講じるものとします。
    </div>
    <div class="mb-4">
      <div class="h5">第7条 アクセス解析ツール</div>
      当方は、お客様のアクセス解析のために、「Googleアナリティクス」を利用しています。
      Googleアナリティクスは、トラフィックデータの収集のためにCookieを使用しています。<br>
      トラフィックデータは匿名で収集されており、個人を特定するものではありません。<br>
      Cookieを無効にすれば、これらの情報の収集を拒否することができます。<br>
      詳しくはお使いのブラウザの設定をご確認ください。<br>
    </div>
    <div class="mb-4">
      <div class="h5">第8条（プライバシーポリシーの変更）</div>
      本ポリシーの内容は，法令その他本ポリシーに別段の定めのある事項を除いて，ユーザーに通知することなく，変更することができるものとします。<br>
      当方が別途定める場合を除いて，変更後のプライバシーポリシーは，本ウェブサイトに掲載したときから効力を生じるものとします。
    </div>
    <div class="mb-4">
      <div class="h5">第9条（免責事項）</div>
      また、本サービスのコンテンツ・情報について、できる限り正確な情報を提供するように努めておりますが、正確性や安全性を保証するものではありません。情報が古くなっていることもございます。<br>
      本サービスに掲載された内容によって生じた損害等の一切の責任を負いかねますのでご了承ください。
    </div>
    <div class="mb-4">
      <div class="h5">第10条（お問い合わせ窓口）</div>
      本ポリシーに関するお問い合わせは，管理者Twitterアカウント(@eityamo)までお願いいたします。
    </div>
    <p class="text-right">以上</p>
    <p>2022年05月19日 制定</p>
  </section>
</div>

app/views/records/terms.html.erb
<% set_meta_tags title: '利用規約', noindex: true
 %>
<div class="container mx-auto mt-24">
  <section class="bg-white m-10 p-10 rounded-lg">
    <div class="h3 text-center mb-5">利用規約</div>
    この利用規約（以下，「本規約」といいます。）は，届け、反抗期（以下，「当方」といいます。）がこのウェブサイト上で提供するサービス（以下，「本サービス」といいます。）の利用条件を定めるものです。登録ユーザーの皆さま（以下，「ユーザー」といいます。）には，本規約に従って，本サービスをご利用いただきます。
    <div class="mb-4">
      <div class="h5">第1条（適用）</div>
      本規約は，ユーザーと当方との間の本サービスの利用に関わる一切の関係に適用されるものとします。
    </div>
    <div class="mb-4">
      <div class="h5">第2条（利用登録）</div>
      本サービスにおいては，登録希望者が本規約に同意の上，当方の定める方法によって利用登録を申請し，当方がこれを承認することによって，利用登録が完了するものとします。<br>
      当方は，利用登録の申請者に以下の事由があると判断した場合，利用登録の申請を承認しないことがあり，その理由については一切の開示義務を負わないものとします。
      <div class="list-decimal mt-2">
        <li>利用登録の申請に際して虚偽の事項を届け出た場合</li>
        <li>本規約に違反したことがある者からの申請である場合</li>
        <li>その他，当方が利用登録を相当でないと判断した場合</li>
      </div>
    </div>
    <div class="mb-4">
      <div class="h5">第3条（プライバシーポリシー）</div>
      当方は，本サービスの利用によって取得する個人情報については，当方「プライバシーポリシー」に従い適切に取り扱うものとします。
    </div>
    <div class="mb-4">
      <div class="h5">第4条（禁止事項）</div>
      ユーザーは，本サービスの利用にあたり，以下の行為をしてはなりません。
      <div class="list-decimal mt-2">
        <li>法令または公序良俗に違反する行為</li>
        <li>犯罪行為に関連する行為</li>
        <li>当方，本サービスの他のユーザー，または第三者のサーバーまたはネットワークの機能を破壊したり，妨害したりする行為</li>
        <li>当方のサービスの運営を妨害するおそれのある行為</li>
        <li>他のユーザーに関する個人情報等を収集または蓄積する行為</li>
        <li>不正アクセスをし，またはこれを試みる行為</li>
        <li>他のユーザーに成りすます行為</li>
        <li>当方のサービスに関連して，反社会的勢力に対して直接または間接に利益を供与する行為</li>
        <li>当方，本サービスの他のユーザーまたは第三者の知的財産権，肖像権，プライバシー，名誉その他の権利または利益を侵害する行為</li>
        <li>以下の表現を含み，または含むと当方が判断する内容を本サービス上に投稿し，または送信する行為</li>
        <li>過度に暴力的な表現</li>
        <li>露骨な性的表現</li>
        <li>人種，国籍，信条，性別，社会的身分，門地等による差別につながる表現</li>
        <li>自殺，自傷行為，薬物乱用を誘引または助長する表現</li>
        <li>その他反社会的な内容を含み他人に不快感を与える表現</li>
        <li>以下を目的とし，または目的とすると当方が判断する行為</li>
        <li>性行為やわいせつな行為を目的とする行為</li>
        <li>面識のない異性との出会いや交際を目的とする行為</li>
        <li>他のユーザーに対する嫌がらせや誹謗中傷を目的とする行為</li>
        <li>当方，本サービスの他のユーザー，または第三者に不利益，損害または不快感を与えることを目的とする行為</li>
        <li>その他本サービスが予定している利用目的と異なる目的で本サービスを利用する行為</li>
        <li>宗教活動または宗教団体への勧誘行為</li>
        <li>その他，当方が不適切と判断する行為</li>
      </div>
    </div>
    <div class="mb-4">
    </div>
    <div class="h5">第5条（本サービスの提供の停止等）</div>
    当方は，以下のいずれかの事由があると判断した場合，ユーザーに事前に通知することなく本サービスの全部または一部の提供を停止または中断することができるものとします。
    .list-decimal.mt-2
    li 本サービスにかかるコンピュータシステムの保守点検または更新を行う場合
    li 地震，落雷，火災，停電または天災などの不可抗力により，本サービスの提供が困難となった場合
    li コンピュータまたは通信回線等が事故により停止した場合
    li その他，当方が本サービスの提供が困難と判断した場合
    li 当方は，本サービスの提供の停止または中断により，ユーザーまたは第三者が被ったいかなる不利益または損害についても，一切の責任を負わないものとします。
    <div class="mb-4">
      <div class="h5">第6条（著作権）</div>
      ユーザーは，自ら著作権等の必要な知的財産権を有するか，または必要な権利者の許諾を得た文章，画像や映像等の情報に関してのみ，本サービスを利用し，投稿ないしアップロードすることができるものとします。<br>
      ユーザーが本サービスを利用して投稿ないしアップロードした文章，画像，映像等の著作権については，当該ユーザーその他既存の権利者に留保されるものとします。ただし，当方は，本サービスを利用して投稿ないしアップロードされた文章，画像，映像等について，本サービスの改良，品質の向上，または不備の是正等ならびに本サービスの周知宣伝等に必要な範囲で利用できるものとし，ユーザーは，この利用に関して，著作者人格権を行使しないものとします。<br>
      前項本文の定めるものを除き，本サービスおよび本サービスに関連する一切の情報についての著作権およびその他の知的財産権はすべて当方または当方にその利用を許諾した権利者に帰属し，ユーザーは無断で複製，譲渡，貸与，翻訳，改変，転載，公衆送信（送信可能化を含みます。），伝送，配布，出版，営業使用等をしてはならないものとします。
    </div>
    <div class="mb-4">
      <div class="h5">第7条（利用制限および登録抹消）</div>
      当方は，ユーザーが以下のいずれかに該当する場合には，事前の通知なく，投稿データを削除し，ユーザーに対して本サービスの全部もしくは一部の利用を制限しまたはユーザーとしての登録を抹消することができるものとします。
      <div class="list-decimal mt-2">
        <li>本規約のいずれかの条項に違反した場合</li>
        <li>登録事項に虚偽の事実があることが判明した場合</li>
        <li>その他，当方が本サービスの利用を適当でないと判断した場合</li>
        <li>当方は，本条に基づき当方が行った行為によりユーザーに生じた損害について，一切の責任を負いません。</li>
      </div>
    </div>
    <div class="mb-4">
      <div class="h5">第8条（保証の否認および免責事項）</div>
      当方は，本サービスに事実上または法律上の瑕疵（安全性，信頼性，正確性，完全性，有効性，特定の目的への適合性，セキュリティなどに関する欠陥，エラーやバグ，権利侵害などを含みます。）がないことを明示的にも黙示的にも保証しておりません。<br>
      当方は，本サービスに起因してユーザーに生じたあらゆる損害について一切の責任を負いません。<br>
      当方は，本サービスに関して，ユーザーと他のユーザーまたは第三者との間において生じた取引，連絡または紛争等について一切責任を負いません。
    </div>
    <div class="mb-4">
      <div class="h5">第9条（サービス内容の変更等）</div>
      当方は，ユーザーに通知することなく，本サービスの内容を変更しまたは本サービスの提供を中止することができるものとし，これによってユーザーに生じた損害について一切の責任を負いません。
    </div>
    <div class="mb-4">
      <div class="h5">第10条（利用規約の変更）</div>
      当方は，必要と判断した場合には，ユーザーに通知することなくいつでも本規約を変更することができるものとします。なお，本規約の変更後，本サービスの利用を開始した場合には，当該ユーザーは変更後の規約に同意したものとみなします。
    </div>
    <div class="mb-4">
      <div class="h5">第11条（通知または連絡）</div>
      ユーザーと当方との間の通知または連絡は，当方の定める方法によって行うものとします。<br>
      当方は,ユーザーから,当方が別途定める方式に従った変更届け出がない限り,現在登録されている連絡先が有効なものとみなして当該連絡先へ通知または連絡を行い,これらは,発信時にユーザーへ到達したものとみなします。<br>
    </div>
    <div class="mb-4">
      <div class="h5">第12条（権利義務の譲渡の禁止）</div>
      ユーザーは，当方の書面による事前の承諾なく，利用契約上の地位または本規約に基づく権利もしくは義務を第三者に譲渡し，または担保に供することはできません。
    </div>
    <div class="mb-4">
      <div class="h5">第13条（準拠法・裁判管轄）</div>
      本規約の解釈にあたっては，日本法を準拠法とします。<br>
      本サービスに関して紛争が生じた場合には，当方の本店所在地を管轄する裁判所を専属的合意管轄とします。
    </div>
    <p class="text-right">以上</p>
    <p>2022年05月19日 制定</p>
  </section>
</div>

app/views/shared/_footer.html.erb
<!-- footer - start -->
<footer class="p-4 bg-indigo-100 rounded-lg shadow md:flex md:items-center md:justify-between md:p-6 dark:bg-gray-800">
    <span class="text-sm text-gray-800 sm:text-center dark:text-gray-400 md:ml-4"><%= t "defaults.footer" %></span>
    <ul class="flex flex-wrap items-center mt-3 text-sm text-gray-500 dark:text-gray-400 sm:mt-0">
        <li>
            <%= link_to  t("defaults.terms"), terms_path, class: "mr-4 hover:underline md:mr-6" %>
        </li>
        <li>
            <%= link_to t("defaults.privacy"), privacy_policy_path, class: "mr-4 hover:underline md:mr-6" %>
        </li>
        <li>
            <%= link_to t("defaults.twitter"), 'https://twitter.com/eityamo', class: "mr-4 hover:underline md:mr-6", target: "_blank", rel: "noopener noreferrer" %>
        </li>
        <li>
            <%= link_to t("defaults.facebook"), 'https://www.facebook.com/eiji.yukihiro.1', class: "mr-4 hover:underline md:mr-6", target: "_blank", rel: "noopener noreferrer" %>
        </li>
    </ul>
</footer>
<!-- footer - end -->